
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 04 20:52:09 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 44;
  public static final int LCBR = 6;
  public static final int LTE = 39;
  public static final int UMINUS = 46;
  public static final int INTEGER = 32;
  public static final int SEMI = 8;
  public static final int CONTINUE = 23;
  public static final int INT = 15;
  public static final int MINUS = 42;
  public static final int STATIC = 13;
  public static final int LT = 37;
  public static final int LP = 2;
  public static final int COMMA = 10;
  public static final int CLASS = 11;
  public static final int RP = 3;
  public static final int MULTIPLY = 43;
  public static final int PLUS = 41;
  public static final int ASSIGN = 34;
  public static final int QUOTE = 33;
  public static final int IF = 19;
  public static final int THIS = 24;
  public static final int DOT = 9;
  public static final int ID = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int LAND = 48;
  public static final int RCBR = 7;
  public static final int LB = 4;
  public static final int RETURN = 18;
  public static final int EQUAL = 35;
  public static final int TRUE = 27;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int RB = 5;
  public static final int LOR = 49;
  public static final int NULL = 29;
  public static final int MOD = 45;
  public static final int BREAK = 22;
  public static final int VOID = 14;
  public static final int GTE = 40;
  public static final int ELSE = 20;
  public static final int WHILE = 21;
  public static final int NEQUAL = 36;
  public static final int CLASS_ID = 31;
  public static final int EXTENDS = 12;
  public static final int STRING = 17;
  public static final int LNEG = 47;
  public static final int FALSE = 28;
  public static final int GT = 38;
  public static final int LENGTH = 26;
}

